### ISSUE TITLE
Parágrafo duplicado

### ISSUE THREAD

**Issue by PedroVenancio** [qgispt/site#38]
O parágrafo seguinte encontra-se duplicado na página eventos:

"Será um dia inteiramente dedicado ao QGIS com apresentações das novidades, casos de estudo nacionais e workshops. Será também o espaço ideal para apresentar o grupo de utilizadores QGIS PT e divulgar os seus objectivos. Além disso, está planeada uma sessão de trabalho para todos os interessados em colaborar com o grupo QGIS PT / QGIS.org"

**Comment by gioman** [comment]
fixed
