### ISSUE TITLE
Proposta de atualização do blog post de transformação de coordenadas

### ISSUE THREAD

**Issue by PedroVenancio** [qgispt/site#40]
Proposta de atualização do blog post transformacao-de-coordenadas-e-utilizacao-das-grelhas-ntv2-no-qgis

https://dl.dropboxusercontent.com/u/5772257/qgis/index.html 

Como o texto é bastante vasto, fica mais estruturado e acessível desta forma. Basicamente acrescenta um índice para aceder diretamente a cada uma das partes do texto, com bookmarks.

**Comment by hfpmartins** [comment]
Pedro,

Já fiz as alterações. Tive que mudar o índice de sítio uma vez que isso
iria entrar em conflito com a maneira como o octopress funciona e gera
excertos dos posts para colocar na listagem de artigos disponíveis. Assim,
mudei o índice para ficar logo a seguir ao primeiro parágrafo.

Só irei publicar esta adaptação quando for publicar a página de eventos
pois também foi preciso mudar algumas coisas no blog para que o link de
ventos apareça na barra de topo.

Abc,

No dia 14 de março de 2015 às 10:28, Pedro Venancio <
notifications@github.com> escreveu:

> Proposta de atualização do blog post
> transformacao-de-coordenadas-e-utilizacao-das-grelhas-ntv2-no-qgis
>
> https://dl.dropboxusercontent.com/u/5772257/qgis/index.html
>
> Como o texto é bastante vasto, fica mais estruturado e acessível desta
> forma. Basicamente acrescenta um índice para aceder diretamente a cada uma
> das partes do texto, com bookmarks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qgispt/site/issues/40>.
>



-- 
Hugo Martins
