### ISSUE TITLE
Mails from subscription form go to spam

### ISSUE THREAD

**Issue by gioman** [qgispt/site#42]
there is something we can do about it?

**Comment by SrNetoChan** [comment]
warn people during the subscription?

"Obrigado pela sua subscrição, irá receber uma confirmação por email. Caso não receba o email dentro de 10 minutos, por favor verifique a sua caixa de spam."

@hfpmartins o email do formulário tb foi actualizado?

**Comment by andremano** [comment]
I think warning is the best option. It's not just with gmail. I tried with my work mail (utwente.nl) and the mail also landed on the SPAM folder. Either we discover what is raising the spam flag or we just highlight the "por favor verifique a sua caixa de spam" with bold red.
